### ISSUE TITLE
Question about running arbitrary command during slug compilation

### ISSUE THREAD

**Issue by w0rm** [localmed/heroku-buildpack-python-extras#2]
Hello, 

first of all I'd like to thank you for this improvement of default python buildpack, because I can't imagine website project to be based on only one programming language. I often use compass gem to compile scss to css, and plan to use requirejs optimiser that runs on nodejs.

I don't want compiled assets to be part of my repository, they'd rather be compiled during app deployment. So I'd like to know if it is possible to run arbitrary command during slug compilation with this buildpack (e.g. `compass compile`). Is it possible?

**Comment by w0rm** [comment]
Never mind, I found out myself that `bin/post_compile`  is run if exists.

**Comment by petebrowne** [comment]
Yeah that's certainly the most straight forward way to do it!

If you're using Django and some kind of asset processing library, like say [django-assetfiles](https://github.com/localmed/django-assetfiles), `collectstatic` will get run automatically. This is how we're using the buildpack.

**Comment by w0rm** [comment]
@petebrowne thanks! I'm using web.py, so `collectstatic` is not an option for me.
